# This is a basic workflow to help you get started with Actions

name: IntegrateDevelop
run-name: IntegrateDevelop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  pull_request:
    branches:
      - develop
    types:
      - closed 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# give permissions to this workflow
permissions:
  contents: write
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "integrateDevelop"
  integrateDevelop:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # set current datetime to a variable
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
      # create a branch, the name of which includes current datetime
      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch develop
          git switch -c integrateDevelop_${{ env.CURRENT_DATETIME }}
          git push -u origin integrateDevelop_${{ env.CURRENT_DATETIME }}
      # open pull requests to integrate
      - name: Create pull request for develop-step2
        uses: repo-sync/pull-request@v2
        with:
          source_branch: integrateDevelop_${{ env.CURRENT_DATETIME }}
          destination_branch: develop-step2
          pr_title: integrateDevelop_step2_${{ env.CURRENT_DATETIME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request for develop-step1-change
        uses: repo-sync/pull-request@v2
        with:
          source_branch: integrateDevelop_${{ env.CURRENT_DATETIME }}
          destination_branch: develop-step1-change
          pr_title: integrateDevelop_step1-change_${{ env.CURRENT_DATETIME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # get target pull requests
      - name: Get target pull requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        run: |
          {
            echo "ALL_PR=(empty)" >> $GITHUB_ENV
            ALL_PR=`gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/tommykey0925/actionTest/pulls`
            echo "ALL_PR"
          } >> $GITHUB_ENV
          echo ${{ env.ALL_PR }}

      # check if the pull request is mergeable

      # approve the PR

      # auto-merge

      # delete the branch if both pull request was closed
      - name: Delete the branch
        run: |
          git switch develop
          git branch -d integrateDevelop_${{ env.CURRENT_DATETIME }}
          git push origin -d integrateDevelop_${{ env.CURRENT_DATETIME }}
